---
# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-python/>.
version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Install flake8
          command: sudo pip install --upgrade flake8
      - run:
          name: Python linter
          command: flake8

  version-bump:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            ./.circleci/check-version-bump.sh

  deploy:
    docker:
      - image: circleci/python:3.7.0
    environment:
      - PYPI_USERNAME: nzlabplus-bot  # here be the name of the Government Innovation Service Lab Pypi account to automatically publish the OpenFisca-Aotearoa package to Pypi
    # - PYPI_PASSWORD: this value will have to be set in CircleCI's web interface; do not set it here, it is a secret!
    steps:
      - run:
          name: Upload package to Pypi if functional changes were made
          command: ./.circleci/deploy-if-version-bump.sh

  build_python2:
    docker:
      - image: python:2.7.14

    steps:
      - checkout

      - restore_cache:
          key: v1-py2-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/aotearoa
            virtualenv /tmp/venv/aotearoa
            echo "source /tmp/venv/aotearoa/bin/activate" >> $BASH_ENV


      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip twine wheel
            pip install --editable .[dev] --upgrade
            pip install -r requirements.txt
            
      - save_cache:
          key: v1-py2-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/aotearoa

      - run:
          name: Run tests
          command: make test

  build_python3:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/aotearoa
            python -m venv /tmp/venv/aotearoa
            echo "source /tmp/venv/aotearoa/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip twine wheel
            pip install --editable .[dev] --upgrade
            pip install -r requirements.txt

      - save_cache:
          key: v1-py3-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/aotearoa

      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - version-bump
      - build_python2
      - build_python3
      # Uncomment the lines below when you have a Pypi account and you are ready to deploy your country package to reusers.
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       # owner: ServiceInnovationLab  # prevent failed builds on forks # This filter is not valid yet in CircleCI 2.0, see <https://discuss.circleci.com/t/20443>
      #       branches:
      #         only: master
