---
# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-python/>.
version: 2
jobs:
  pythonlint:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install flake8
          command: sudo pip install --upgrade flake8
      - run:
          name: Python linter
          command: flake8
  yamllint:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: sudo pip install --upgrade yamllint
      - run:
          name: Yaml linter
          command: yamllint .
  version-bump:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            ./.circleci/check-version-bump.sh

  deploy:
    docker:
      - image: circleci/python:3.7.2
    environment:
      # here be the name of the Government Innovation Service Lab Pypi account
      # to automatically publish the OpenFisca-Aotearoa package to Pypi
      - PYPI_USERNAME: nzlabplus-bot
    # - PYPI_PASSWORD: this value will have to be set in CircleCI's web interface; do not set it here, it is a secret!
    steps:
      - run:
          name: Upload package to Pypi if functional changes were made
          command: ./.circleci/deploy-if-version-bump.sh

  build_python3:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ checksum "setup.py" }}-{{checksum "requirements.txt"}}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/aotearoa
            python -m venv /tmp/venv/aotearoa
            echo "source /tmp/venv/aotearoa/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip twine wheel
            pip install --editable .[test] --upgrade
            pip install -r requirements.txt

      - save_cache:
          key: v1-py3-{{ checksum "setup.py" }}-{{checksum "requirements.txt"}}
          paths:
            - /tmp/venv/aotearoa

      - run:
          name: Run tests
          command: make test

  tag_release:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: "git tag the release"
          command: "./.circleci/git_tag.sh"

workflows:
  version: 2
  build_and_test:
    jobs:
      - pythonlint
      - yamllint
      - version-bump
      - build_python3
      - tag_release:
          requires:
            - version-bump
            - build_python3
          filters:
            branches:
              only: master
