---
# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-python/>.
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Allow cache restore
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages

      - restore_cache:
          environment:
          key: cache-root-{{ checksum "setup.py" }}

      - run:
          name: Install wheel
          command: sudo pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11

      - run:
          name: Install execution dependencies
          command: sudo pip install .[test] --upgrade

      - run:
          name: Install deployment dependencies
          command: sudo pip install twine

      - save_cache:
          key: cache-root-{{ checksum "setup.py" }}
          paths:
            - /usr/local/lib/python2.7/site-packages/
            - /usr/local/bin

      - run:
          name: Run tests
          command: make test

  lint:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install flake8
          command: sudo pip install --upgrade flake8
      - run:
          name: Python linter
          command: flake8

  version-bump:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            ./.circleci/check-version-bump.sh

  deploy:
    docker:
      - image: circleci/python:3.6.6
    environment:
      - PYPI_USERNAME: nzlabplus-bot  # here be the name of the Government Innovation Service Lab Pypi account to automatically publish the OpenFisca-Aotearoa package to Pypi
    # - PYPI_PASSWORD: this value will have to be set in CircleCI's web interface; do not set it here, it is a secret!
    steps:
      - run:
          name: Upload package to Pypi if functional changes were made
          command: ./.circleci/deploy-if-version-bump.sh


workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
      - version-bump
      # Uncomment the lines below when you have a Pypi account and you are ready to deploy your country package to reusers.
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       # owner: ServiceInnovationLab  # prevent failed builds on forks # This filter is not valid yet in CircleCI 2.0, see <https://discuss.circleci.com/t/20443>
      #       branches:
      #         only: master
